import numpy as np
#排序、条件筛选函数
a = np.array([[3,7],[9,1]])
print(a)
print(np.sort(a))
print (np.sort(a, axis =  0))
dt=np.dtype([('name','S10'),('age',int)])
a=np.array([("raju",21),("anil",25),("ravi",  17),  ("amar",27)], dtype = dt)
print(a)
print (np.sort(a, order =  'name'))
#numpy.argsort() 函数返回的是数组值从小到大的索引值
print()
x = np.array([3,  1,  2])
print(x)
y=np.argsort(x)
print(y)
print(x[y])
#numpy.lexsort() 用于对多个序列进行排序
print()
nm =  ('raju','anil','ravi','amar')
dv =  ('f.y.',  's.y.',  's.y.',  'f.y.')
ind=np.lexsort((dv,nm))
print(ind)
print ([nm[i]  +  ", "  + dv[i]  for i in ind])
#numpy.argmax() 和 numpy.argmin()函数分别沿给定轴返回最大和最小元素的索引
print()
a = np.array([[30,40,70],[80,20,10],[50,90,60]])
print(a)
print (np.argmax(a))
print (np.argmax(a,axis=0))
print (np.argmax(a,axis=1))
minindex=np.argmin(a)
print(minindex)
print(a.flatten()[minindex])
print (np.argmin(a,axis=0))
#numpy.nonzero() 函数返回输入数组中非零元素的索引
print()
a = np.array([[30,40,0],[0,20,10],[50,0,60]])
print(a)
print(np.nonzero(a))
#numpy.where() 函数返回输入数组中满足给定条件的元素的索引
print()
x = np.arange(9.).reshape(3,  3)
print(x)
y=np.where(x>3)
print(y)
print(x[y])
#numpy.extract() 函数根据某个条件从数组中抽取元素，返回满条件的元素
print()
x = np.arange(9.).reshape(3,  3)
print(x)
condition=np.mod(x,2)==0
print(condition)
print(np.extract(condition,x))